# @name get-prompts
GET http://localhost:3333/prompts


####

# @name Upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

####

# @name Create-transcription
post http://localhost:3333/videos/3e608e52-68f5-4979-bc63-ff32aaf1d90a/transcription
Content-Type: application/json

{
  "prompt":"clean arquiteture, ddd"
}

####

# @name Generate-ai-completion
post http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId":"3e608e52-68f5-4979-bc63-ff32aaf1d90a",
  "temperature":0.5,
  "template":"Gere um resumo sucinto da transcricao do video informado a seguir:'''{transcription}'''"
}

